# Generated by Django 2.0.8 on 2019-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, verbose_name='Model')),
                ('fabricante', models.CharField(max_length=30, verbose_name='Maker')),
                ('cilindrada', models.CharField(max_length=30, verbose_name='Displacement')),
                ('potencia_maxima', models.CharField(blank=True, max_length=30, verbose_name='Maximum power')),
                ('periodo_comercializacion', models.CharField(blank=True, max_length=30, verbose_name='Marketing period')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('D', 'Deportivo'), ('A', 'Aventurero'), ('R', 'Rutero')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='moto',
            field=models.ManyToManyField(to='main.Moto'),
        ),
    ]
