# Generated by Django 2.0.8 on 2019-01-22 17:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190122_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Moto')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='urlFoto',
            field=models.URLField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='rating',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
