# Generated by Django 2.0.8 on 2019-01-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
